/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiEmailEnquiryTriageRouteImport } from './routes/ai-email-enquiry-triage'
import { Route as ConsultantEngagementPipelineRouteImport } from './routes/consultant-engagement-pipeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmailEnquiryTriageRoute = AiEmailEnquiryTriageRouteImport.update({
  id: '/ai-email-enquiry-triage',
  path: '/ai-email-enquiry-triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantEngagementPipelineRoute =
  ConsultantEngagementPipelineRouteImport.update({
    id: '/consultant-engagement-pipeline',
    path: '/consultant-engagement-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-email-enquiry-triage': typeof AiEmailEnquiryTriageRoute
  '/consultant-engagement-pipeline': typeof ConsultantEngagementPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-email-enquiry-triage': typeof AiEmailEnquiryTriageRoute
  '/consultant-engagement-pipeline': typeof ConsultantEngagementPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-email-enquiry-triage': typeof AiEmailEnquiryTriageRoute
  '/consultant-engagement-pipeline': typeof ConsultantEngagementPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ai-email-enquiry-triage' | '/consultant-engagement-pipeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-email-enquiry-triage' | '/consultant-engagement-pipeline'
  id:
    | '__root__'
    | '/'
    | '/ai-email-enquiry-triage'
    | '/consultant-engagement-pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiEmailEnquiryTriageRoute: typeof AiEmailEnquiryTriageRoute
  ConsultantEngagementPipelineRoute: typeof ConsultantEngagementPipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-email-enquiry-triage': {
      id: '/ai-email-enquiry-triage'
      path: '/ai-email-enquiry-triage'
      fullPath: '/ai-email-enquiry-triage'
      preLoaderRoute: typeof AiEmailEnquiryTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant-engagement-pipeline': {
      id: '/consultant-engagement-pipeline'
      path: '/consultant-engagement-pipeline'
      fullPath: '/consultant-engagement-pipeline'
      preLoaderRoute: typeof ConsultantEngagementPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiEmailEnquiryTriageRoute: AiEmailEnquiryTriageRoute,
  ConsultantEngagementPipelineRoute: ConsultantEngagementPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
